axis_linear: 1  # Left thumb stick vertical
scale_linear: 1
scale_linear_turbo: 1.5

axis_angular: 0  # Left thumb stick horizontal
scale_angular: 1

enable_button: 0  # X button
enable_turbo_button: 5  # RB (Right Button)
